### ISSUE TITLE
New taurus-4.3.0 problem with remote tango host?

### ISSUE THREAD

**Issue by CorF4** [taurus-org/taurus#715]
Hello, 
I have tried to update from taurus-4.1.1 to the current development version (basically 4.3.0, as I understand). However, in my setup I have a remote tango host. I can connect to the tango database with other applications (like Jive). The TANGO_HOST is specified in /etc/tangorc. Both local and remote hosts are Ubuntu 17.10 machines. With the new taurus version I get the following warning when trying to open a gui:

`MainThread     WARNING  2018-03-01 13:45:32,290 dev-VirtualBox:10000.ps/power/sim1: Could not create HW object: device ps/power/sim1 not defined in the database !`

Where dev-VirtualBox is the local host. So I am guessing the application is searching the wrong database, i.e. the local host's database instead of the remote host's. Why does this happen? Is there anything I am missing regarding the tango_host setup? Here I am just launching a python script that launches the gui. If I specify tango://host_ip:10000/ps/power/sim1 as the model it also does not work.
What has changed in the meanwhile? 
Thanks for your help!

**Comment by cpascual** [comment]
Hi,

We are routinely using taurus with remote tango hosts here, so I suspect some configuration issue in your case.

In order to help in debugging (and eventually for us to reproduce it), can you please try using a TangoTest device server and a simple client (e.g. a taurusform).

Also can you test with PyTango:

```python
import tango
d = tango.DeviceProxy('sys/tg_test/1')  # if it works, try also with "ps/power/sim1"
print d.read_attribute('state')
```
and then with taurus:

```python
import taurus
d = taurus.Device('sys/tg_test/1')
print d.stateObj.read()
```

**Comment by CorF4** [comment]
Hi,
thanks for your quick reply!

So, running the TangoTest and some of my own device servers:

setting up PyTango.DeviceProxy and reading the state works with both sys/tg_test/1 and ps/power/sim1.

Problems appear when using taurus:

If I do this: `taurusform sys/tg_test/1`

A window pops up when I click 'Show Device' with `tango://dev-VirtualBox:10000/sys/tg_test/1 not available` and on the terminal this:

> MainThread     INFO     2018-03-02 08:55:47,201 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2018-03-02 08:55:47,457 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/icon/)
MainThread     WARNING  2018-03-02 08:55:50,408 TaurusRootLogger: /usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/util/tauruswidgetfactory.py:111: DeprecationWarning: TaurusConsole is deprecated since 4.0.4. Use silx.gui.console.IPythonWidget instead
  m = __import__(module_name, fromlist=['*'], level=0)
MainThread     WARNING  2018-03-02 08:55:50,508 TaurusRootLogger: Problem with taurus.qt.editor (hint: is spyder >=3 installed?)
MainThread     WARNING  2018-03-02 08:55:50,521 TaurusDevicePanel: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/panel/taurusdevicepanel.py", line 315, in setModel
    taurus.Device(model).ping()  # TODO: Tango-centric
  File "/usr/lib/python2.7/dist-packages/tango/green.py", line 264, in greener
    ret = submitter(fn, self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tango/green.py", line 100, in submit
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tango/device_proxy.py", line 1289, in __DeviceProxy__ping
    return self._ping(*args, **kwargs)
ConnectionFailed: DevFailed[
DevError[
    desc = Device sys/tg_test/1 is not exported (hint: try starting the device server)
  origin = DeviceProxy::get_corba_name()
  reason = API_DeviceNotExported
severity = ERR]
]

When trying with taurus in python:

>  import taurus
 d = taurus.Device('sys/tg_test/1')
 print d.stateObj.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/taurus/core/tango/tangoattribute.py", line 526, in read
    raise df
PyTango.DevFailed: DevFailed[
DevError[
    desc = Failed to connect to device sys/tg_test/1
           The connection request was delayed.
           The last connection request was done less than 1000 ms ago
  origin = Connection::reconnect
  reason = API_CantConnectToDevice
severity = ERR]
DevError[
    desc = Failed to read_attribute on device sys/tg_test/1, attribute state
  origin = DeviceProxy::read_attribute()
  reason = API_AttributeFailed
severity = ERR]
] 

and trying the same command again:

>  PyTango.ConnectionFailed: DevFailed[
DevError[
    desc = Device sys/tg_test/1 is not exported (hint: try starting the device server)
  origin = DeviceProxy::get_corba_name()
  reason = API_DeviceNotExported
severity = ERR]
DevError[
    desc = Failed to read_attribute on device sys/tg_test/1, attribute state
  origin = DeviceProxy::read_attribute()
  reason = API_AttributeFailed
severity = ERR]
]

And when trying the same with my own device:

> import taurus
 d = taurus.Device('ps/power/sim1')
MainThread     WARNING  2018-03-02 09:03:51,416 dev-VirtualBox:10000.MAGPower1: Could not create HW object: device ps/power/sim1 not defined in the database !

**Comment by cpascual** [comment]
This is all very strange.  It works for me here on a debian9 (which should be pretty similar to ubuntu17), on a SUSE Leap and on Win7...

I suspect some network config issue (specially since you are using a VirtualBox).

Maybe try to set up the TANGO_HOST environment variable with `export TANGO_HOST=<...>`

Also maybe try to put there a fully qualified domain name...

Does it work if you try the commands in the local box where the tango DB is running?

**Comment by CorF4** [comment]
Thanks for the suggestion. If I run the the TangoTest on the same machine, I get the same error that it cannot recognize that the device server is running (PyTango is still fine). So, seems it may not be related to the remote host (at least not entirely, since the taurus.Device('ps/power/sim') also doesn't work). 

Any more ideas? Thanks a lot!

(Actually, the two virtual boxes have the same names, just used the IP and export TANGO_HOST=IP:10000 didn't help. )

**Comment by cmft** [comment]
Hi @CorF4 ,
Can you run this snippet?
```
from taurus.core.tango.tangovalidator import TangoDeviceNameValidator
print TangoDeviceNameValidator().getUriGroups('ps/power/sim')
```

**Comment by CorF4** [comment]
That's the output I get:
`{'fragment': None, '_devalias': None, 'devname': 'ps/power/sim1', 'authority': None, '__STRICT__': True, 'host': None, '_devslashname': 'ps/power/sim1', 'query': None, 'path': 'ps/power/sim1', 'scheme': 'tango', 'port': None}
`

**Comment by cmft** [comment]
Hi @CorF4 , 
Sorry. I expected something different . It is right.

Can you try this?

```
from taurus import Authority
print Authority()
print Authority().fullname
```

**Comment by CorF4** [comment]
Here is what I get:
>from taurus import Authority
 print Authority()
TangoAuthority(//dev-VirtualBox:10000)
 print Authority().fullname
tango://dev-VirtualBox:10000

**Comment by cmft** [comment]
Ok ,
It seems that could be any problem with FQDN (the fullname should show the domain name) but It could be not defined in a VM.
Can you try this?
```
```
from taurus import Authority
aut =  Authority()
d = aut.getDevice("ps/power/sim1")
print d.alive()
print d.host()
``` 
I found a bug in the TangoAuthority, I created a PR #719, but I don't think so that it solves your problem, but can you test it anyway.

**Comment by CorF4** [comment]
Hi,
so, here is the output again:
```
>>> from taurus import Authority
>>> aut = Authority()
>>> dev = aut.getDevice("ps/power/sim1")
>>> print dev.alive()
MainThread     WARNING  2018-03-05 13:03:12,914 dev-VirtualBox:10000.PowerSim1: Could not create HW object: device ps/power/sim1 not defined in the database !
MainThread     WARNING  2018-03-05 13:03:12,990 dev-VirtualBox:10000.PowerSim1: Could not create HW object: device ps/power/sim1 not defined in the database !
False
>>> print dev.host()
dev-virtualbox
```

I also checked the TangoAuthority correction, but it doesn't help. Actually, gives this error upon invoking d.alive():
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' has no attribute 'alive'
```

trying with sys/tg_test/1 (when running locally) gives the output that the device server is not alive...

**Comment by cmft** [comment]
Thanks, this is good. It seems that PyTango  could not create the DB with some FQDN name.
Can you execute this code:

```
from PyTango import (Database, ApiUtil)
import socket


def get_default_tango_host():
    if hasattr(ApiUtil, "get_env_var"):
        f = ApiUtil.get_env_var
    else:
        f = get_env_var
    return f("TANGO_HOST")


host, port = get_default_tango_host().split(":")

host = socket.getfqdn(host)
print host
# This code should not work
db = Database(host, port)
db.dev_name() 
```

**Comment by CorF4** [comment]
Ok, seems my issue is solved for now...I had accidentally used the same host_names for both virtual machines (though didn't think it would be a problem). I changed them now to different names and now it seems to work with the new taurus-4.3.0 as well...

PS: the code from above runs fine now.

**Comment by cpascual** [comment]
> Ok, seems my issue is solved for now...I had accidentally used the same host_names for both virtual machines (though didn't think it would be a problem). I changed them now to different names and now it seems to work with the new taurus-4.3.0 as well...

Ok, glad to hear that it is solved. It makes sense that if the hostname was the same the Tango connexion would fail.
