### ISSUE TITLE
Taurus4 regression: cannot read TangoAttribute uchar_image_ro

### ISSUE THREAD

**Issue by NexeyaSGara** [taurus-org/taurus#359]
Hi,

On Windows machine, with Taurus 4.0.1 

When settting the model of a TaurusImageDialog with an image of type uint8, it failed to show the image.

The problem seems to be in the taurusvaluestable.py, getting 'rvalue is invalid' Exception in setModel method. 

It can be reproduces using the TangoTest device.

**Comment by cpascual** [comment]
Can you please send exactly the command to reproduce with TangoTest?

**Comment by NexeyaSGara** [comment]
`taurusdevicepanel sys/tg_test/1` then clicking on the button "show" for uchar_image.

I'm getting this exception

![image](https://cloud.githubusercontent.com/assets/2578703/21848890/4ef74592-d803-11e6-9a16-00c83c77d2e8.png)

**Comment by cpascual** [comment]
I am not getting that exception under linux... I tried with both taurus 4.0.1 and 4.0.3-alpha...

I'll need to get a windows machine to test... not easy right now

**Comment by NexeyaSGara** [comment]
If id a taurusimage /sys/tg_test/1/uchar_image_ro

![image](https://cloud.githubusercontent.com/assets/2578703/21850429/db8754f0-d80a-11e6-81e7-da1b67e10db6.png)

instead of that

![image](https://cloud.githubusercontent.com/assets/2578703/21850472/061f89f8-d80b-11e6-8c64-454dec7fec51.png)

**Comment by cpascual** [comment]
I managed to reproduce it. The key is that `uchar_image` works, but `uchar_image_ro` does not.

I get the following exception with `uchar_image_ro`:

~~~
$  taurusform 'sys/tg_test/1/uchar_image_ro'

(...)
### Clicking on "show"
(...)
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/button/taurusbutton.py", line 223, in onClicked
    self.widget().setModel(self.getModelName())
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/table/taurusvaluestable.py", line 707, in setModel
    raise Exception('rvalue is invalid')
~~~

Now that I can reproduce it I'll try to debug it

**Comment by NexeyaSGara** [comment]
Ok.

Just for the record, I tried with taurus 3.6 
`taurusform 'sys/tg_test/1/uchar_image_ro'`
It works "normally" but it's an array viewer instead of the image viewer

**Comment by cpascual** [comment]
The problem seems to be a regression in the taurus core. 
Taurus 4 fails to read read a read-only uchar attribute

~~~
In [1]: import taurus

In [2]: taurus.Attribute('sys/tg_test/1/uchar_image_ro').read()
MainThread     WARNING  2017-01-11 16:41:52,742 TaurusRootLogger: Unknown unit "No unit (will be treated as dimensionless)"
MainThread     WARNING  2017-01-11 16:41:52,865 TaurusRootLogger: Unknown unit "No unit (will be treated as dimensionless)"
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-e8e5b191038c> in <module>()
----> 1 taurus.Attribute('sys/tg_test/1/uchar_image_ro').read()

/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/tangoattribute.py in read(self, cache)
    505                 self.__attr_value, self.__attr_err = None, e
    506                 self.debug("[Tango] read failed: %s", e)
--> 507                 raise e
    508         elif self.__subscription_state in (SubscriptionState.Subscribing, SubscriptionState.PendingSubscribe):
    509             self.__subscription_event.wait()

AttributeError: 'NoneType' object has no attribute 'view'

~~~

The same command works well with taurus 3.7.3.

So I will edit the title of the issue

**Comment by cpascual** [comment]
> It works "normally" but it's an array viewer instead of the image viewer

Yes, that is what is expected.

The reason for this is that `uchar` can be used both representing "characters" (one-char ascii strings) as well as for short insigned integers (uint8). The Tango plugin in Taurus chooses to decode uchars as "characters" (and hence, the taurusform uses a table for viewing them)...

This has lead to many discussions in the past, and since there was no consensus we decided to leave things as they are. But feel free to re-open the discussion (a new TEP would be the appropriate place for that) since it is clearly an unsolved thing. 

That said, note that you can use the `view()` method of the numpy arrays to change the interpretation. So for example, you can plot the `uchar_image` attribute with something like:

~~~
taurusimage 'eval:{sys/tg_test/1/uchar_image}.view("uint8")'
~~~

**Comment by cpascual** [comment]
This PR should solve the issue: https://github.com/taurus-org/taurus/issues/362

**Comment by NexeyaSGara** [comment]
Hi,

I applied the modifications.

With the taurusdevicepanel on tangotest, I can now have the windows opened on uchar_image, but the "array view".

I still can't have the image displayed. 
I tried
`taurusimage 'eval:{sys/tg_test/1/uchar_image}.view("uint8")'`
but it doesn't launch anything, I tried to do it by hand in changeing taurusmodel in the taurusimage widget, but it doesn't validate the expression 'eval:{sys/tg_test/1/uchar_image}.view("uint8")'

**Comment by cpascual** [comment]
> With the taurusdevicepanel on tangotest, I can now have the windows opened on 
> uchar_image, but the "array view".

Ok, so I would say that for what concerns to *this* issue, the PR fixes the problem.

I understand that what remains now is related to the interpretation of uchar as characters instead of uint8, which as I said is currently the *intended* behaviour, but which can be open for discussion (in that case, please open a TEP for that).

**Comment by NexeyaSGara** [comment]
Ok.

For now, we reverted to taurus 3.7.3 and we have our unit8 image displayed in a taurusImageDialog "normally" like we expected.

So we can keep it as the deault behaviour but maybe have a option to display uchar as uint8.

Thanks

**Comment by cpascual** [comment]
Please do not give up on Taurus4  :) 
let's open an issue to deal with this either at core or at taurusImageDialog level...

**Comment by NexeyaSGara** [comment]
I don't give up, but for the moment, that's our fix to have a good demo :)

I let you open a new issue about it

**Comment by cpascual** [comment]
I created an issue (#367), and note that I changed my mind (after [this comment](https://github.com/taurus-org/taurus/pull/362#issuecomment-272448315) from @teresanunez and  some discussion with @cmft ) and we will revert to the uint8 interpretation.
